environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install mocha
  - npm install istanbul
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
  - npm install coveralls
  - type .\coverage\lcov.info | node ./node_modules/coveralls/bin/coveralls.js
version: "{build}"
